# Generated by Django 4.1.2 on 2022-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, default='images/question-mark.png', null=True, upload_to='images/'),
        ),
    ]
